# Stage 1: Build
FROM node:22-alpine as builder
WORKDIR /app
COPY package*.json ./
COPY client/package*.json ./client/
RUN npm ci --prefix client
COPY . .
RUN cd client && node ./node_modules/vite/bin/vite.js build

# Stage 2: Serve
FROM nginx:alpine
COPY --from=builder /app/client/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
