FROM node:18-slim
WORKDIR /app
COPY package*.json ./
RUN apt-get update && apt-get install -y --no-install-recommends python3 make g++ && \
    npm ci --omit=dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
COPY . .
EXPOSE 3020
CMD ["node", "server/index.js"]
